---
- hosts: k8-cluster
  tasks:
    # Create a sprintboot namespace on the cluster using ansible.
    - name: "Create a k8s namespace"
      kubernetes.core.k8s:
        name: sprintboot
        api_version: v1
        kind: Namespace
        state: present

    # Copying the Pod.yaml and deployment.yaml in the remote node.
    - name: "copying springboot-deployment.yml with playbook to k8"
      copy:
        src: springboot-deployment.yml
        dest: /tmp/springboot-deployment.yml
    - name: "copying springboot-service.yml with playbook to k8"
      copy:
        src: springboot-service.yaml
        dest: /tmp/springboot-service.yaml

    # Creating a Kubernetes deployment in test using file stored locally
    - name: "Play springboot-deployment.yml in k8"
      k8s:
        state: present
        namespace: sprintboot
        src: /tmp/springboot-deployment.yml

    # Creating a Kubernetes deployment in test using file stored locally
    - name: "Play springboot-service.yaml in k8"
      k8s:
        state: present
        namespace: sprintboot
        src: /tmp/springboot-service.yaml

    # CleanUP all the applied configurations
    - name: "Ansible file module to delete multiple files"
      file:
        path: "{{ item }}"
        state: absent   # to delete the files
      with_items:
      - /tmp/springboot-deployment.yml
      - /tmp/springboot-service.yaml