kind: Service
apiVersion: v1
metadata:
  name: springboot-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.220
  selector:
    app: springboot
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080



#spec:
#  selector:
#    app: springboot
#  ports:
#    - name: http
#      protocol: TCP
#      nodePort: 31317
#      port: 8080
#      targetPort: 8080
#  type: NodePort
