kind: Service
apiVersion: v1
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - name: http
      protocol: TCP
      nodePort: 31317
      port: 8080
      targetPort: 8080
  type: NodePort