apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        #image: cloudtechmasters/springboot-maven-course-micro-svc:#{Build.BuildId}#
        image: 1youssefbaroudi1/pringboot-maven:Image_BuildNumber
        ports:
        - containerPort: 8080
